campaign1 = Campaign.create!(name: "Voting Campaign 2023")
volunteer1 = Volunteer.create!(name: "Phil", phone: "7202768836")
volunteer2 = Volunteer.create(name: "Riley", phone: "17203178790")
volunteer3 = Volunteer.create(name: "Jason", phone: "18563716283")
volunteer4 = Volunteer.create(name: "Andrea", phone: "16303034646")
CampaignVolunteer.create!(campaign: campaign1, volunteer: volunteer1)
CampaignVolunteer.create!(campaign: campaign1, volunteer: volunteer2)
CampaignVolunteer.create!(campaign: campaign1, volunteer: volunteer3)
CampaignVolunteer.create!(campaign: campaign1, volunteer: volunteer4)
Message.create!(text: "Don't forget to vote!!!", campaign: campaign1)